apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: ivsonv/gitops
  newTag: c7e16387617ca47c8013a22f13ab9a695e89a7d3
